name: Ensure code quality

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  code-quality:
    # Name the Job
    name: Ensure code quality
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Lint using eslint
        run: yarn eslint .

      - name: Check code formatting
        run: yarn prettier --check .

      - name: Check typescipt typings
        run: yarn tsc -p tsconfig.json --noEmit
