name: Ensure code quality

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  code-quality:
    # Name the Job
    name: Ensure code quality
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            .yarn
            node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --cache-folder .yarn --frozen-lockfile

      - name: Lint using eslint
        run: yarn eslint .

      - name: Check code formatting
        run: yarn prettier --check .

      - name: Check typescipt typings
        run: yarn tsc -p tsconfig.json --noEmit
